### ISSUE TITLE
Receiving permission denied for docker-backup

### ISSUE THREAD

**Issue by fstelte** [muesli/docker-backup#10]
Folllowed the guide, installed GO and executed go build on two dockerhosts. On one host all works fine. Second one I receive 
`-bash: ./docker-backup: Permission denied`

Retried pulling and building again.
Info:
Ubunutu server 20.04.01
Working docker version: 19.03.13
Not working docker version: 19.03.8

**Comment by muesli** [comment]
What are the permissions of `./docker-backup` in that case?

**Comment by fstelte** [comment]
it's 
'-rwxrwxr-x+  1 user user 12949057 Dec  4 09:55 docker-backup'

and when I sudo ./docker-backup I receive 'sudo: unable to execute ./docker-backup: Permission denied'

odd thing is that when I enter ./docker-b and use tab for autocomplete on the one host it does autocomplete (where docker-backup works) on the other host it doesn't autocomplete

**Comment by muesli** [comment]
Is the filesystem mounted with the `noexec` option, by chance?

**Comment by fstelte** [comment]
ok so some extra information, seems to be working on the other host now. I had the docker-backup solution in the same place as all my persistant storage.
For one host that is in my home directory, for the other it is on a mount with additional storage so the path for that host was /mnt/hdd/files/docker-backup

I just now moved the solution to ~/docker-backup and now everything works..

**Comment by fstelte** [comment]
> Is the filesystem mounted with the `noexec` option, by chance?

Yes it is, I am changing that right now

**Comment by muesli** [comment]
Yeah, that's it then.
