### ISSUE TITLE
WARNING: DOESN'T BACKUP FILES

### ISSUE THREAD

**Issue by Tiebe** [muesli/docker-backup#11]
This did NOT backup my (in this case: homeassistant) files!! I lost hours of work just because of this. Leaving this warning out here so others don't do the same as me!

**Comment by muesli** [comment]
Could you try and be a bit more specific as to what happened - or what didn't happen?

**Comment by Tiebe** [comment]
I backed up using this tool, but it didn't backup my files, maybe I had to specify some kind of option so it would have outputted a jar instead of a json file. The only thing it did was output a json and a .files file, but when restoring, it restored to container with the same settings, but did not restore the files.

**Comment by muesli** [comment]
I'm truly sorry that you lost some of your data, but this is actually well documented in the README:

`This will create a .json file with the container's metadata, as well as a file containing all the volumes that need to be backed up with an external tool like restic or borgbackup.`

If you want to directly create a .tar file containing all the container's data, simply run `docker-backup` with `--tar`.
