### ISSUE TITLE
docker-backup not a recognized command

### ISSUE THREAD

**Issue by thedinz** [muesli/docker-backup#17]
After installing everything.... I feel successful, I got no errors to speak of.

It still will not work, when I run any docker-backup command I get

'docker-backup' is not recognized as an internal or external command,
operable program or batch file.

Any idea what I could have missed? I installed go, I installed docker-backup from the GIT, thats about all there was for install instructions.

**Comment by thedinz** [comment]
trying to start over I see this when using the GIT

# github.com/muesli/docker-backup
.\backup.go:82:28: undefined: syscall.Stat_t

**Comment by muesli** [comment]
Did the `go build` succeed? If so, you should have a `docker-binary` binary in your working dir. Call that:

```
./docker-backup ...
```

**Comment by thedinz** [comment]
no this is what i get during build, did not catch the last part the first time.

```
go: downloading github.com/docker/docker v0.7.3-0.20190503020752-619df5a8f60f
go: downloading github.com/docker/go-connections v0.4.0
go: downloading github.com/kennygrant/sanitize v1.2.4
go: downloading github.com/spf13/cobra v0.0.3
go: downloading github.com/docker/go-units v0.4.0
go: downloading github.com/docker/distribution v2.7.1+incompatible
go: downloading github.com/opencontainers/go-digest v1.0.0-rc1
go: downloading github.com/pkg/errors v0.9.1
go: downloading golang.org/x/net v0.0.0-20190502183928-7f726cade0ab
go: downloading github.com/inconshreveable/mousetrap v1.0.0
go: downloading github.com/spf13/pflag v1.0.3
go: downloading github.com/opencontainers/image-spec v1.0.1
go: downloading github.com/sirupsen/logrus v1.4.1
go: downloading google.golang.org/grpc v1.20.1
go: downloading github.com/Microsoft/go-winio v0.4.16
go: downloading github.com/gogo/protobuf v1.2.1
go: downloading github.com/konsorten/go-windows-terminal-sequences v1.0.1
go: downloading github.com/golang/protobuf v1.2.0
go: downloading google.golang.org/genproto v0.0.0-20180817151627-c66870c02cf8
go: downloading golang.org/x/sys v0.0.0-20190916202348-b4ddaad3f8a3
# github.com/muesli/docker-backup
.\backup.go:82:28: undefined: syscall.Stat_t
```

**Comment by muesli** [comment]
Which operating system is this on?

**Comment by thedinz** [comment]
windows 10

**Comment by muesli** [comment]
Oh, I see. I'm afraid there's no Windows support as of now. I guess it should be possible to add that, but I'd need someone else to write and test it.
