### ISSUE TITLE
docker-backup: command not found

### ISSUE THREAD

**Issue by dbalegends** [muesli/docker-backup#28]
I am not able to install on Ubuntu 20.04, please help me to resolve it.

root@dockerub:~# cd docker-backup
root@dockerub:~/docker-backup# go build
go: downloading github.com/docker/docker v0.7.3-0.20190503020752-619df5a8f60f
go: downloading github.com/docker/go-connections v0.4.0
go: downloading github.com/kennygrant/sanitize v1.2.4
go: downloading github.com/spf13/cobra v0.0.3
go: downloading golang.org/x/net v0.0.0-20190502183928-7f726cade0ab
go: downloading github.com/spf13/pflag v1.0.3
go: downloading github.com/docker/go-units v0.4.0
go: downloading github.com/opencontainers/image-spec v1.0.1
go: downloading github.com/docker/distribution v2.7.1+incompatible
go: downloading github.com/sirupsen/logrus v1.4.1
go: downloading google.golang.org/grpc v1.20.1
go: downloading github.com/gogo/protobuf v1.2.1
go: downloading github.com/opencontainers/go-digest v1.0.0-rc1
**go: downloading github.com/pkg/errors v0.9.1**
go: downloading golang.org/x/sys v0.0.0-20190916202348-b4ddaad3f8a3
go: downloading github.com/golang/protobuf v1.2.0
go: downloading google.golang.org/genproto v0.0.0-20180817151627-c66870c02cf8
root@dockerub:~/docker-backup# docker-backup --help
docker-backup: command not found
root@dockerub:~/docker-backup# ^C

**Comment by muesli** [comment]
You've only built the binary, it's not available in your `$PATH` yet. You can run it from the current working directory with:

```bash
./docker-backup --help
```

**Comment by dbalegends** [comment]
@muesli thanks, it's working

and docker-backup --help  will work if we set the $PATH:
export PATH=$PATH:/root/docker-backup/
