### ISSUE TITLE
archive/tar: write too long

### ISSUE THREAD

**Issue by barto95100** [muesli/docker-backup#7]
Hi thank's for your dev

when i test to backup a container a receive this error message : 

archive/tar: write too long

do you have idea for workaround ?

**Comment by kgnfth** [comment]
Same

**Comment by mike-crawfurd** [comment]
I have the same but it seems to be caused for me as it is trying to 'backup' / 'tar' my timezone?
For dockers where I do not control the time, the backup is fine. Is there a way to exclude /etc/localtime?

Adding /etc/localtime
archive/tar: write too long
